[package]
name = "ember_validation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ember_core = { path = "../ember_core" }
ember_project = { path = "../ember_project" }
ember_documents = { path = "../ember_documents" }
ember_capabilities = { path = "../ember_capabilities" }
ember_assets = { path = "../ember_assets" }
ember_packages = { path = "../ember_packages" }
serde_json.workspace = true
