[package]
name = "ember_app_shell"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ember_core = { path = "../ember_core" }
ember_project = { path = "../ember_project" }
ember_documents = { path = "../ember_documents" }
ember_editor_core = { path = "../ember_editor_core" }
serde.workspace = true
serde_json.workspace = true
